# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.debug=false

# Sets the proper version for the Deobfuscator Table - called Parchment
neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17



#####   ENVIRONMENT PROPERTIES   #####

# The Minecraft version - must agree with the Neo version to get a valid artifact
minecraft_version=1.21.1

# The Minecraft version range this mod works with - can use any release version of Minecraft as bounds.
minecraft_version_range=[1.21.1,1.22)

# The NeoForge version - must agree with the Minecraft version to get a valid artifact
neo_version=21.1.147

# The NeoForge version this mod works with - range can use any version of NeoForge as bounds
neo_version_range=[21.1.0,)

# The loader version range - can only use the major version of FML as bounds
loader_version_range=[4,)



#####   MOD PROPERTIES   #####

# The unique mod identifier for the mod.
mod_id=casinocraft

# The human-readable display name for the mod.
mod_name=CasinoCraft

# The license of the mod.
mod_license=All Rights Reserved

# The mod version.
mod_version=1.0

# The group ID for the mod.
mod_group_id=mod.casinocraft

# The author of the mod.
mod_authors=Epidra2077

# The description of the mod. This is a simple multiline text string that is used for display purposes in the mod list.
mod_description=Lorem ipsum dolor sit amet,\nconsetetur sadipscing elitr,\nsed diam nonumy eirmod tempor invidunt\nut labore et dolore magna aliquyam erat,\nsed diam voluptua.
