modLoader="javafml"
loaderVersion="[37,)" #mandatory
license="All rights reserved"
issueTrackerURL="https://github.com/Epidra/CasinoCraft/issues"
[[mods]]
modId="casinocraft"
version="15.0"
displayName="CasinoCraft"
displayURL="https://www.curseforge.com/minecraft/mc-mods/casinocraft"
logoFile="logo.png"
credits="Thanks for this example mod goes to Java" #optional
authors="Love, Cheese and small house plants" #optional
description='''
Ever wanted to relax with a little card game after a hard day in the mines?
Or lose all your potatoes on the roulette table?
Then you're at the right place.
'''
[[dependencies.casinocraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"
[[dependencies.casinocraft]]
    modId="lucky77"
    mandatory=true
    versionRange="[1.0,)"
    ordering="NONE"
    side="BOTH"