modLoader="javafml"
loaderVersion="[47,)" #mandatory
license="All rights reserved"
issueTrackerURL="https://github.com/Epidra/CasinoCraft/issues"
[[mods]]
modId="casinocraft"
version="21.0"
displayName="CasinoCraft"
displayURL="https://www.curseforge.com/minecraft/mc-mods/casinocraft"
logoFile="logo.png"
credits="To whoever creates CC0 licensed assets" #optional
authors="Epidra2077" #optional
description='''
Ever wanted to relax with a little card game after a hard day in the mines?
Or lose all your potatoes on the roulette table?
Then you're at the right place.
'''
[[dependencies.casinocraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
[[dependencies.casinocraft]]
    modId="lucky77"
    mandatory=true
    versionRange="[4.0,)"
    ordering="NONE"
    side="BOTH"